development:
  adapter: mysql2
  database: octablog
  pool: 5
  timeout: 5000
  user: root
  password:

test:
  adapter: mysql2
  database: octablog
  pool: 5
  timeout: 5000
  user: root
  password:


production:
  adapter: mysql2
  database: octablog
  pool: 5
  timeout: 5000
  user: root
  password:

